Styled buttons for the new landing page.
thisisobate/notaryproject.dev pull request #2
Opened 2022-12-15 19:43 UTC by hamees-sayed

2023-01-09 09:38 UTC, thisisobate requested changes
Great work! @hamees-sayed 
I left a few suggestions for you to improve.
We're so close to merging this one 😄

2023-01-09 09:38 UTC, thisisobate commented on assets/scss/_buttons.scss
> +}
```suggestion
.flex .button {
    font-size: 1.5rem;
    color: $white;
    font-weight: $font-weight-bold;
    border: none;
    padding: 0.6em 1.5em;
    border-radius: 39px;
}
```

2023-01-09 09:38 UTC, thisisobate commented on assets/scss/_buttons.scss
> +}
remove block as it's already taken effect in `.button` class

2023-01-09 09:38 UTC, thisisobate commented on content/en/_index.html
> +          <a class="get-started">
I think you should remove the `get-started` class since you already apply the same styling to the child element.

2023-01-09 09:38 UTC, thisisobate commented on content/en/_index.html
> +          <a class="demo">
Same applies to this one

2023-01-09 10:16 UTC, hamees-sayed commented on assets/scss/_buttons.scss
> +    font-size: 1.5rem;
I agree. 1.5rem looked unfitting to me as well. 1rem looks good

2023-01-09 10:58 UTC, hamees-sayed commented on assets/scss/_buttons.scss
> +    font-size: 1.5rem;
after applying all the changes that you suggested, I think 1.25rem would be good. 1rem looks too small
| 1.25rem             |  1rem letters |
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/98336593/211292692-cdf94b3b-919c-4aff-bb76-e72b93205c48.png)  |  ![image](https://user-images.githubusercontent.com/98336593/211292786-0294fcf2-b725-450e-bf25-a31dd1ac7182.png)

2023-01-09 11:34 UTC, hamees-sayed commented on assets/scss/_buttons.scss
> +    font-size: 1.5rem;
Yeah, I agree as well. 1rem looks more in line with the above title and subtitle.

2023-01-10 04:29 UTC, thisisobate approved these changes
Please move these unrelated changes to a separate branch. 
Otherwise, LGTM!

2023-01-10 04:29 UTC, thisisobate commented on assets/scss/_styles_project.scss
> +  margin: 2em 0;
This is a totally different feature. I would advise you to make this change in a separate PR

2023-01-10 04:29 UTC, thisisobate commented on content/en/_index.html
> +
move to separate PR

2023-01-10 04:30 UTC, thisisobate commented on assets/scss/_buttons.scss
> +    font-size: 1.5rem;
Please do well to resolve conversations; helps to keep the PR discussions clean

2023-01-10 08:33 UTC, hamees-sayed commented
Understood, I will keep this in mind. I have made the necessary changes and will create a separate PR for the feature card component 👍

2023-01-10 14:51 UTC, merged

2023-01-10 14:51 UTC, thisisobate commented
Thank you for your contribution! @hamees-sayed