created and styled feature card component
thisisobate/notaryproject.dev pull request #4
Opened 2023-01-11 09:33 UTC by hamees-sayed

2023-01-16 14:45 UTC, thisisobate requested changes
Great work! @hamees-sayed 
I left a few suggestions for you to consider. Let me know when you address them and I'll approve right away!

2023-01-16 14:45 UTC, thisisobate commented on assets/scss/_styles_project.scss
> +  font-size: 3rem;
`3rem` looks a bit too much. Try reducing the size to fit with the rest of the document.

2023-01-16 14:45 UTC, thisisobate commented on assets/scss/_styles_project.scss
> +  font-size: 2.25rem;
Same here. Reduce the size to fit with the rest of the document

2023-01-16 14:45 UTC, thisisobate commented on assets/scss/_styles_project.scss
> +  font-size: 2rem;
same here...reduce size

2023-01-16 14:45 UTC, thisisobate commented on content/en/_index.html
> +  </div>
Add padding around this section. You can take a look at how it's done in the `adopted and trusted` section: [https://github.com/thisisobate/notaryproject.dev/blob/bb629d8417c82e4c4b2ba5a1963d8f362a244b90/content/en/_index.html#L107](https://github.com/thisisobate/notaryproject.dev/blob/bb629d8417c82e4c4b2ba5a1963d8f362a244b90/content/en/_index.html#L107)

2023-01-16 15:12 UTC, hamees-sayed commented on assets/scss/_styles_project.scss
> +  font-size: 2rem;
Is it okay if I also resize the entire box? 
![image](https://user-images.githubusercontent.com/98336593/212710433-04a824cd-c271-40bf-b946-07d0e14621c7.png)

2023-01-17 07:47 UTC, thisisobate approved these changes
LGTM! Thanks a bunch! @hamees-sayed

2023-01-17 07:51 UTC, merged